version: "3"
services:
  wordpress:
    build:
      context: ./config/php
    container_name: wordpress_${COMPOSE_PROJECT_NAME}
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${WORDPRESS_REPO}:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    container_name: db_${COMPOSE_PROJECT_NAME}
    image: mysql
    #command: --lower_case_table_names=1
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  phpmyadmin:
    container_name: phpmyadmin_${COMPOSE_PROJECT_NAME}
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: ${PMA_USER}
      UPLOAD_LIMIT: 64M
    ports:
      - ${PMA_PORT}:80
    restart: always
    depends_on:
      - db

  nginx:
    build:
      context: ./config/nginx
      args:
        WORDPRESS_PORT: ${WORDPRESS_PORT}
    container_name: nginx_${COMPOSE_PROJECT_NAME}
    depends_on:
      - wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - ${WORDPRESS_REPO}:/var/www/html
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${CERTS_DIR}:/etc/letsencrypt
    restart: always

